### ISSUE TITLE
Fix migrations CI for SQLite

### ISSUE THREAD

**Issue by ychiucco** [fractal-analytics-platform/fractal-server#1163]
The execution order at the moment is
```yaml
- name: Apply migration and fix-db script (postgres)
  run: ...
- name: Convert postgres database into sqlite
  run: pipx run db-to-sqlite[postgresql]==1.5 "postgresql://postgres:postgres@localhost/fractal_test" $ROOTDIR/clean_db_fractal_${TARGET_VERSION}.sql.sqlite3 --all
 - name: Apply migration and fix-db script (sqlite)
```

but in this way the sqlite action is done on an already up-to-date database.
