### ISSUE TITLE
Clean up submodule

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#523]
See failing CI here: https://github.com/fractal-analytics-platform/fractal-server/actions/runs/4240798460/jobs/7370368689

**Comment by tcompa** [comment]
We could not solve this issue, but we are switching to a different coverage-reporting github action. If/when #522 is merged, this issue will be closed.

**Comment by tcompa** [comment]
Notice that the github-action fix (in #522, thanks @mfranzon) was to set the fetch depth at the beginning of the coverage job with
```yaml
  coverage:
    name: Coverage
    runs-on: ubuntu-20.04
    needs: tests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1000
          submodules: "recursive"
```
