### ISSUE TITLE
Clean up docs

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#809]
(based on @ychiucco's work in the tasks repo)

**Comment by tcompa** [comment]
Based on work in the tasks/client repo's, we should also clean up the docs here.

- Prune any unnecessary dependency from both `docs/docs-requirements.txt` and `{pyproject.toml, poetry.lock}`
- Update GitHub actions:
    - Remove the docs part from the CI github action into an independent documentation.yaml, and also remove the creation of openapi.json
    - Copy the excat github action we have in tasks/client
    - Add a new preliminary job that: (1) install poetry, (2) set-up python, (3) `poetry install --without dev --with doc`, (4) create openapi.json
- Make the mkdocs.yml configuration (and docs folder) as similar as possible to the ones in tasks/client:
    - add extra.css, and the new css info in mkdocs.yml
    - make `handlers/python` options as similar as possible to the others
    - make `theme/features` as similar as possible (e.g. add `content.code.copy`)
    - make `site_name` specific ("Fractal Server"?)
    - add copyright footer
    - ... (anything else which can make the three docs homogeneous)
    - anything else which is needed to have three homogeneous docs pages for the three projects

**Comment by tcompa** [comment]
The relevant openapi block will look like
```
      - name: extract openapi schema
        env:
          DEPLOYMENT_TYPE: development
          JWT_SECRET_KEY: 1234
          DATA_DIR_ROOT: /tmp/fractal-server/
          FRACTAL_TASKS_DIR: /tmp/fractal-server/tasks/
          FRACTAL_RUNNER_WORKING_BASE_DIR: /tmp/fractal-server/artifacts/
        run: fractalctl openapi --openapi-file docs/openapi.json
```
